# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cqcb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cqcb
  pod ’AFNetworking'
  pod ’SDWebImage'
  pod ’MJRefresh'
  pod ’MJExtension'
  pod 'IQKeyboardManager'
  pod ‘Masonry’
  pod ‘MWPhotoBrowser’
  pod ‘MBProgressHUD’
  pod ‘SDCycleScrollView’

end
